quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/academico
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.sql-load-script=no-file
quarkus.hibernate-orm.log.sql=true

quarkus.oidc.auth-server-url=http://keycloak:8080/realms/academico-realm
quarkus.oidc.client-id=admin-api
quarkus.oidc.credentials.secret=admin-secret
quarkus.oidc.application-type=service
quarkus.oidc.token.audience=admin-api

quarkus.http.auth.policy.roles.roles-allowed=admin,coordenador,professor,aluno

quarkus.http.auth.permission.roles.paths=/*
quarkus.http.auth.permission.roles.policy=roles

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

quarkus.http.port=8082
quarkus.http.host=0.0.0.0
