FROM node:20 AS build
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM nginx:alpine
COPY --from=build /app/dist/ui-manager /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
